[package]
authors = ["Keli <root@keli.im>"]
edition = "2018"
name = "totp-cli"
version = "0.1.0"

[dependencies]
dirs = "2.0.2"
google-authenticator = "0.3.0"
serde = {version = "1.0.104", features = ["derive"]}
toml = "0.5.6"
