[package]
name = "totp-cli"
version = "0.1.0"
authors = ["Keli <root@keli.im>"]
edition = "2018"

[dependencies]
toml = "0.5.6"
oath = "0.10.2"
serde = { version = "1.0.104", features = ["derive"] }
dirs = "2.0.2"
